#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
# Gradle 从 android/key.properties 读取（rootProject = android/），
# 写到仓库根会生成一个 Gradle 根本看不到的文件，本地 release 仍回落 debug 签名。
ENV_FILE="android/key.properties"

banner "SunsetRipple release signing"

stage "Check release tools"
say "This creates the long-lived Android release key used by every future update."
if [[ ! -f "settings.gradle.kts" ]]; then
  warn "Run this wizard from the SunsetRipple repository root."
  exit 1
fi
JAVA_HOME_FOR_BASH="${JAVA_HOME:-}"
if [[ -n "$JAVA_HOME_FOR_BASH" ]] && command -v cygpath >/dev/null 2>&1; then
  JAVA_HOME_FOR_BASH=$(cygpath -u "$JAVA_HOME_FOR_BASH")
fi
if [[ -n "$JAVA_HOME_FOR_BASH" && -x "${JAVA_HOME_FOR_BASH}/bin/keytool.exe" ]]; then
  KEYTOOL="${JAVA_HOME_FOR_BASH}/bin/keytool.exe"
elif [[ -n "$JAVA_HOME_FOR_BASH" && -x "${JAVA_HOME_FOR_BASH}/bin/keytool" ]]; then
  KEYTOOL="${JAVA_HOME_FOR_BASH}/bin/keytool"
elif command -v keytool >/dev/null 2>&1; then
  KEYTOOL=$(command -v keytool)
else
  warn "keytool was not found. Set JAVA_HOME to JDK 17 and run the wizard again."
  exit 1
fi
step "Keep the generated PKCS12 release key backed up securely. Losing it prevents future app updates."
pause "I understand. Press Enter to continue."

stage "Choose key identity"
ask storeFile "Keystore path [~/.android/sunset-ripple-release.p12]:"
storeFile=${storeFile:-"$HOME/.android/sunset-ripple-release.p12"}
ask keyAlias "Key alias [sunset-ripple]:"
keyAlias=${keyAlias:-sunset-ripple}
ask KEY_DNAME "Certificate identity [CN=SunsetRipple, OU=Mobile, O=SunsetRipple, C=CN]:"
KEY_DNAME=${KEY_DNAME:-"CN=SunsetRipple, OU=Mobile, O=SunsetRipple, C=CN"}
while true; do
  ask_secret storePassword "Keystore password (12+ characters):"
  if [[ ${#storePassword} -ge 12 ]]; then break; fi
  warn "Use at least 12 characters."
done
ask_secret STORE_PASSWORD_CONFIRM "Repeat the password:"
if [[ "$storePassword" != "$STORE_PASSWORD_CONFIRM" ]]; then
  warn "Passwords do not match. Run the wizard again."
  exit 1
fi

stage "Generate and verify key"
if [[ -f "$storeFile" ]]; then
  say "An existing keystore was found at $storeFile; it will be reused."
else
  confirm "Generate the release keystore at $storeFile?" || exit 1
  mkdir -p "$(dirname "$storeFile")"
  "$KEYTOOL" -genkeypair -v \
    -keystore "$storeFile" \
    -storetype PKCS12 \
    -storepass "$storePassword" \
    -alias "$keyAlias" \
    -keypass "$storePassword" \
    -keyalg RSA \
    -keysize 4096 \
    -validity 36500 \
    -dname "$KEY_DNAME"
fi
keyPassword="$storePassword"
"$KEYTOOL" -list -keystore "$storeFile" -storepass "$storePassword" -alias "$keyAlias" >/dev/null
write_env storeFile "$storeFile"
write_env storePassword "$storePassword"
write_env keyAlias "$keyAlias"
write_env keyPassword "$keyPassword"
say "The key and local signing properties were verified."
note "Back up $storeFile and keystore.properties outside this repository."

stage "Wire the release key into CI"
say "Release 流水线必须能自己拿到签名材料，否则 flutter build apk --release"
say "会静默回落到 debug 签名——每个 release 的签名都不同，用户无法覆盖升级。"
note "这四个值会写进 GitHub Actions repository secrets（gh 未登录则跳过并提示手工补）。"

BASE64_STORE=$(base64 < "$storeFile" | tr -d '\n')
set_secret ANDROID_KEYSTORE_BASE64 "$BASE64_STORE"
set_secret ANDROID_KEYSTORE_PASSWORD "$storePassword"
set_secret ANDROID_KEY_ALIAS "$keyAlias"
set_secret ANDROID_KEY_PASSWORD "$keyPassword"
say "CI secrets 已就绪：release.yml 会还原 $storeFile 并写入 $ENV_FILE。"

finish
